name: photo_view
description: Photo View provides a gesture sensitive zoomable widget. Photo View is largely used to show interactive images and other stuff such as SVG.
version: 0.14.0
homepage: https://github.com/renancaraujo/photo_view
publish_to: "none"

environment:
  sdk: ">=3.0.0 <=4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
